spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL:validate}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
        show_sql: ${SHOW_SQL:false}
      jdbc:
        batch_size: 50
      order_inserts: true
      order_updates: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}

  security:
    secret-key: ${SECRET_KEY}
    access-exp: ${ACCESS_EXP}
    refresh-exp: ${REFRESH_EXP}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    region:
      static: ${AWS_REGION:ap-northeast-2}
      auto: false
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME:simtong}
    ses:
      source: ${SES_SENDER}

domain:
  model:
    user:
      default-image: ${USER_DEFAULT_IMAGE}
    authcode:
      exp: ${AUTHCODE_EXP}
    authcodelimit:
      exp: ${AUTHCODELIMIT_EXP}
      verified-exp: ${AUTHCODELIMIT_VERIFIED_EXP}
      max-attempt-count: ${AUTHCODELIMIT_MAX_ATTEMPT_COUNT}
    spot:
      head: ${HEAD_SPOT}
    holiday:
      week-holiday-limit: ${WEEK_HOLIDAY_LIMIT}
      annual-leave-limit: ${ANNUAL_LEAVE_LIMIT}

fcm:
  value: ${FCM_VALUE}