server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  jackson:
    property-naming-strategy: SNAKE_CASE

  security:
    secret-key: ${SECRET_KEY:asdfasfdasfadsf}
    access-exp: ${ACCESS_EXP:180}
    refresh-exp: ${REFRESH_EXP:180}

domain:
  user:
    default-image: ${USER_DEFAULT_IMAGE:}
  authcode:
    expired: ${AUTHCODE_EXPIRED:180}
  authcodelimit:
    expired: ${AUTHCODELIMIT_EXPIRED:1800}
    verified-expired: ${AUTHCODELIMIT_VERIFIED_EXPIRED:2700}
    max-attempt-count: ${AUTHCODELIMIT_MAX_ATTEMPT_COUNT:5}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: prod