spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL:validate}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
        show_sql: ${SHOW_SQL:false}
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    region:
      static: ${AWS_REGION:ap-northeast-2}
      auto: false
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME:simtong}
    ses:
      source: ${SES_SENDER}