server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  jackson:
    property-naming-strategy: SNAKE_CASE

  security:
    secret-key: ${SECRET_KEY:asdfasfdasfadsf}
    access-exp: ${ACCESS_EXP:180}
    refresh-exp: ${REFRESH_EXP:180}


domain:
  model:
    user:
      default-image: ${USER_DEFAULT_IMAGE:TODO}
    authcode:
      expired: ${AUTHCODE_EXPIRED:1234567890}
    authcodelimit:
      expired: ${AUTHCODELIMIT_EXPIRED:1234567890}
      verified-expired: ${AUTHCODELIMIT_VERIFIED_EXPIRED:1234567890}
      max-attempt-count: ${AUTHCODELIMIT_MAX_ATTEMPT_COUNT:12345}


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: prod