spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:simtong}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  redis:
    port: 6379
    host: localhost

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    region:
      static: ${AWS_REGION:ap-northeast-2}
      auto: false
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME:simtong}
    ses:
      source: ${SES_SENDER}