server:
  port: 8888
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  jackson:
    property-naming-strategy: SNAKE_CASE

  security:
    secret-key: ${SECRET_KEY:asdfasfdasfadsf}
    access-exp: ${ACCESS_EXP:180}
    refresh-exp: ${REFRESH_EXP:180}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: prod