server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: prod