name: "Todo"
description: "할 일이 있으신가요? 🙋‍️"
labels: feat
body:

  - type: textarea
    attributes:
      label: Describe
      description: |
        [설명] 작업에 관한 설명을 작성해주세요.
      placeholder: |
        - [ ] <!-- 작업 내용 작성 -->
        - [ ] <!-- 작업 내용 작성 -->
  - type: textarea
    attributes:
      label: Additional
      description: |
        [추가사항] 별도로 알려줘야 할 사항이나 추가사항을 작성해주세요.
      placeholder: |
        - <!-- 추가사항 작성 -->
        - <!-- 추가사항 작성 -->