name: "Refactor"
description: "개선이 필요해요 ♻️"
labels: refactor
body:

  - type: textarea
    attributes:
      label: AS-IS
      description: |
        [설명] 개선이 필요한 점에 관한 설명을 작성해주세요.
      placeholder: |
        - <!-- 개선 내용 작성 -->
        - <!-- 개선 내용 작성 -->
  - type: textarea
    attributes:
      label: TO-BE
      description: |
        [개선] 개선할 방안에 관한 설명을 작성해주세요.
      placeholder: |
        - <!-- 개선 방안 작성 -->
        - <!-- 개선 방안 작성 -->
  - type: textarea
    attributes:
      label: Additional
      description: |
        [추가사항] 별도로 알려줘야 할 사항이나 추가사항을 작성해주세요.
      placeholder: |
        - <!-- 추가사항 작성 -->
        - <!-- 추가사항 작성 -->