object DependencyVersions {
    const val JWT_VERSION = "0.9.1"
    const val MAPSTRUCT_VERSION = "1.5.2.Final"
    const val AWS_VERSION = "2.2.6.RELEASE"
    const val REDIS_VERSION = "2.7.2"
    const val SERVLET = "4.0.1"
    const val AWS_SES_VERSION = "1.12.296"
    const val SPRING_TRANSACTION = "5.3.22"
    const val S3MOCK = "0.2.4"
    const val QUERYDSL = "5.0.0"
    const val BYTE_BUDDY = "1.12.18"
    const val COMMONS_IO = "2.11.0"
    const val POI_VERSION = "5.2.3"
    const val FIREBASE_ADMIN_VERSION = "9.1.0"
}